---
-
  hosts: all

  tasks:
    - name: Do MMR
      realtime_server:
        server_type: 'MMR'
        action: "{{ item }}"
      loop: 
        - 'suspend'
        - 'update_executable'
        - 'unsuspend'
    - name: Do ZC
      realtime_server:
        server_type: 'ZC'
        action: "{{ item }}"
      loop: 
        - 'suspend'
        - 'update_executable'
        - 'unsuspend'

    - name: All done
      local_action: debug msg="All done"
      run_once: True
